# Site settings
title: Fotograbben
email: wr222ae@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Check out my Github to see all the cool stuff i have made or contributed to.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  vincesthehuman

# Build settings
markdown: kramdown
